name: Base Docker Publish
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build kube-scheduler
        run: make

      - name: Use docker buildx
        run: docker buildx create --use

      - name: Build & Push Image
        env:
          VERSION: ${{ inputs.version }}
        run: docker buildx build --platform linux/amd64,linux/arm64 -t jongbeomlee/kube-scheduler:latest --push .
