name: Base Docker Publish
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Istall GKlib
        run: |
          git clone https://github.com/KarypisLab/GKlib.git && \
          cd GKlib && \
          make config && \
          make && \
          make install && \
          cd .. && \
          rm -rf GKlib

      - name: Install Metis
        run: |
          git clone https://github.com/KarypisLab/METIS.git && \
          cd METIS && \
          sudo apt-get install build-essential && \
          sudo apt-get install cmake && \
          make config shared=1 cc=gcc prefix=~/local && \
          make install && \
          cd .. && \
          rm -rf METIS

      - name: Build kube-scheduler
        run: make

      - name: Use docker buildx
        run: docker buildx create --use

      - name: Build & Push Image
        env:
          VERSION: ${{ inputs.version }}
        run: docker buildx build --platform linux/amd64,linux/arm64 -t jongbeomlee/kube-scheduler:latest --push .
